config/routes.rb
Wenyan::Application.routes.draw do
  root :to => "posts#index"
  get "posts/index"

  match "posts/show/:id" => "posts#show" , :as => :posts_show

  match "posts/new"

  match "posts/remove"

  match "posts/check"

  match "posts/result"

  get "posts/users"

  get "posts/list_authors"

  post "posts/add_author"

  post "posts/remove_author"

  get "posts/list_textbooks"

  post "posts/add_textbook"

  post "posts/remove_textbook"

  get "posts/list_terms"

  post "posts/add_term"

  post "posts/remove_term"

  match "new_user" => "posts#new_user", :as => :new_user

  get "articles.json" => "posts#update_list", :as => :articles

  get "article/:id.json" => "posts#update_article", :as => :article

  get "result_check.json" => "posts#answer_check", :as => :result_check

  get "result_stats.json" => "posts#answer_stats", :as => :result_stats

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :author_id, :content, :id, :info, :term_id, :textbook_id, :title, :subtitle
  belongs_to :author
  belongs_to :textbook
  belongs_to :term
  has_many :sentences
  has_many :words, :through => :sentences
end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :detail, :id, :name
  has_many :articles
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  attr_accessible :fail_count, :id, :pass_count, :sentence_id
  belongs_to :sentence
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
  attr_accessible :article_id, :content, :id, :translation
  belongs_to :article
  has_many :words
  has_one :exam
end

app/models/term.rb
class Term < ActiveRecord::Base
  attr_accessible :id, :title
  has_many :articles
end

app/models/textbook.rb
class Textbook < ActiveRecord::Base
  attr_accessible :id, :title
  has_many :articles
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :id, :location, :textbook, :username, :install_time, :imei, :os, :os_version, :resolution_x, :resolution_y, :user, :token
end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :content, :id, :kind, :mistakes, :sentence_id, :translation
  belongs_to :article
  belongs_to :sentence
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new

    if request.post?
    # render :text => params

    @article = Article.new(params[:article])
    @article.save

    params[:sentences].each do |s|
      sentence = Sentence.new :content => s[:content], :translation => s[:translation]
      sentence.article_id = @article.id
      sentence.save
      if  s[:words]
        s[:words].each do |w|
          word = Word.new(:content => w[:content], :translation => w[:translation], :kind => w[:kind], :mistakes => w[:mistakes])
          word.sentence_id = sentence.id
          word.save
        end
      end
    end

    redirect_to posts_show_path(@article)

    end
  end

  def remove
    article = Article.find(params[:id])
    article.delete()
    render :text => :ok
  end


  def users
    @users = User.all
  end

  def list_authors
    @authors = Author.all
  end

  def add_author
    author = Author.create(:name => params[:name],:detail => params[:detail])
    render :text => author.id
  end

  def remove_author
    author = Author.find(params[:id])
    author.delete()
    render :text => :ok
  end


  def list_textbooks
    @textbooks = Textbook.all
  end

  def add_textbook
    textbook = Textbook.create(:title => params[:name])
    render :text => textbook.id
  end

  def remove_textbook
    textbook = Textbook.find(params[:id])
    textbook.delete()
    render :text => :ok
  end


  def list_terms
    @terms = Term.all
  end

  def add_term
    term = Term.create(:title => params[:name])
    render :text => term.id
  end

  def remove_term
    term = Term.find(params[:id])
    term.delete()
    render :text => :ok
  end

  def api_intro
  end

  # actions for api

  def new_user
    @user = User.create(params[:user])
    @user.token = rand.to_s
    @user.save
    render :text => @user.token
  end

  def update_list
    @articles = Article.all

    render :json => @articles.to_json(
      :except => [:author_id, :term_id, :textbook_id, :content],
      :include => {
        :author =>{:only => [:id, :name, :detail]}, 
        :term => {:only => [:id, :title]}, 
        :textbook => {:only => [:id, :title]}})
  end

  def update_article
    @article = Article.find(params[:id])

    render :json => @article.to_json(
      :except => [:author_id, :term_id, :textbook_id],
      :include => {
        :sentences => {:include => :words},
        :author =>{:only => [:id, :name, :detail]}, 
        :term => {:only => [:id, :title]}, 
        :textbook => {:only => [:id, :title]},
        :words =>  { :except => []} 
        })
  end

  def answer_check
    @exam = Exam.where(:sentence_id => params[:sentence_id]).first_or_create
    @exam.fail_count += 1
    @exam.save
    render :text => '{"result" : true}'
  end

  def answer_stats
    @exams = Exam.all
    render json: @exams
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>文言文内容管理</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/flat-ui.css" rel="stylesheet">
    <link rel="shortcut icon" href="/images/favicon.ico">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
    <![endif]-->

    
    <!-- Load JS here for greater good =============================-->
    <script src="/js/jquery-1.8.2.min.js"></script>
    <script src="/js/jquery-ui-1.10.0.custom.min.js"></script>
    <script src="/js/jquery.dropkick-1.0.0.js"></script>
    <script src="/js/custom_checkbox_and_radio.js"></script>
    <script src="/js/custom_radio.js"></script>
    <script src="/js/jquery.tagsinput.js"></script>
    <script src="/js/bootstrap-tooltip.js"></script>
    <script src="/js/jquery.placeholder.js"></script>
    <script src="/js/application.js"></script>
    <!--[if lt IE 8]>
      <script src="js/icon-font-ie7.js"></script>
      <script src="js/icon-font-ie7-24.js"></script>
    <![endif]-->

    <style>
      body { padding-top: 60px; }
      .relax { margin-right: 5px; margin-left: 5px;}
      span.tag {line-height:30px;margin-right: 5px !important;margin-top: 4px !important;}
      a {color: white;
text-decoration: none;}
    </style>

    <%= csrf_meta_tags %>
  </head>

  <body>


    <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
              <div class="container">
                <div class="brand">文言文后台管理系统</div>
                <div class="nav-collapse collapse">
                  <ul class="nav">
                    <li >
                      <a href="#">
                        管理
                      </a>
                      <ul>
                        <li><a href="<%= posts_new_path %>">添加文章</a></li>
                        <li><a href="<%= posts_index_path %>">文章列表</a></li>
                        <li><a href="<%= posts_list_textbooks_path %>">教科书管理</a></li>
                        <li><a href="<%= posts_list_terms_path %>">学期管理</a></li>
                        <li><a href="<%= posts_list_authors_path %>">作者管理</a></li>
                        <li><a href="<%=  %>">API说明</a></li>
                      </ul> <!-- /Sub menu -->
                    </li>
                  </ul>
                </div><!--/.nav-collapse -->
              </div>
            </div>
          </div>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/posts/check.html.erb
<h1>Posts#check</h1>
<p>Find me in app/views/posts/check.html.erb</p>

app/views/posts/index.html.erb
<h1>文章列表<span class="fui-plus-16" style="margin:20px;"></span></h1>

<div class="container">
	<div class="row">
		<div class="span8">
			<% @articles.each do |article| %>
			<div class="row">
				
				<h5 class="palette palette-firm" id="<%= article.id %>">
					<%= link_to article.title, posts_show_path(article) %>
					<span class="fui-new-24 pull-right hide"></span>
					<span class="fui-cross-24 pull-right delete"></span>
				</h5>
							
			</div>
			<% end %>
		</div>
	</div>
</div>


<script>
$(function(){
	$("body").delegate(".delete", "click", function(data){
		var target = this.parentElement.parentElement;
		console.log(target)
		$.post("/posts/remove", {'id':this.parentElement.id}, function(data){
			target.remove();
		})
	})
})
</script>

app/views/posts/list_authors.html.erb
<h1>作者列表</h1>

<div class="container">

	<div class="row">
		
		<h5 class="">
			<input type="text" value="" placeholder="" id="new-author">
			<div class="btn" id="add-author">添加</div>
			<div class="btn" id="cancel-add">取消</div>
		</h5>
		  <div class="control-group">
		    <label class="control-label" for="editor">介绍</label>
		    <div class="controls">
		      <textarea id="detail" rows="10" column="100" class="input-xxlarge" name="detail" ></textarea>
		    </div>
		  </div>

					
	</div>

	<div class="row">
		<div id="authors" class="span8">
			<% @authors.each do |author| %>
			<div class="row">
				
				<h5 class="palette palette-firm author" id="<%= author.id %>">
					<span><%= author.name %></span>
					<span class="fui-new-24 pull-right relax hide"></span>
					<span class="fui-cross-24 pull-right relax delete"></span>
					<div class="detail-info hide"><%= author.detail %></div>
				</h5>
			</div>
			<% end %>

		</div>
	</div>


</div>

<script>
$(function(){
	$("#add-author").click(function(){

		$.post("/posts/add_author", {'name':$("#new-author").val(),'detail':$("#detail").val()}, function(data){
				$("#authors").append('<div class="row"><h5 class="palette palette-firm author" id="'+ data +'"><span> ' + $("#new-author").val() + ' </span><span class="fui-new-24 pull-right relax hide"></span><span class="fui-cross-24 pull-right relax delete"></></span><div class="detail-info hide">' + $("#detail").val() + '</div></h5></div>');

				$("#new-author").val('');
		})
	})


	$("#cancel-add").click(function(){
		$("#new-author").val('')
	})

	$("body").delegate(".delete", "click", function(data){
		
		console.log(this.parentElement.id);
		var target = this.parentElement.parentElement;


		$.post("/posts/remove_author", {'id':this.parentElement.id}, function(data){
				target.remove();
		})

	})

	$("body").delegate(".author", "click", function(){
		var target = this.children[3];
		$(target).toggle()
	})
})
</script>

app/views/posts/list_terms.html.erb
<h1>学期列表</h1>

<div class="container">


			<div class="row">
				
				<h5 class="">
					<input type="text" value="" placeholder="" id="new-term">
					<div class="btn" id="add-term">添加</div>
					<div class="btn" id="cancel-add">取消</div>
				</h5>
							
			</div>

	<div class="row">
		<div id="terms" class="span8">
			<% @terms.each do |term| %>
			<div class="row">
				
				<h5 class="palette palette-firm" id="<%= term.id %>">
					<span><%= term.title %></span>
					<span class="fui-new-24 pull-right relax hide"></span>
					<span class="fui-cross-24 pull-right relax delete"></span>
				</h5>
			</div>
			<% end %>

		</div>
	</div>


</div>

<script>
$(function(){
	$("#add-term").click(function(){

		$.post("/posts/add_term", {'name':$("#new-term").val()}, function(){
				$("#terms").append('<div class="row"><h5 class="palette palette-firm"><span> ' + $("#new-term").val() + ' </span><span class="fui-new-24 pull-right relax hide"></span><span class="fui-cross-24 pull-right relax delete"></></span></h5></div>');

				$("#new-term").val('')
		})
	})


	$("#cancel-add").click(function(){
		$("#new-term").val('')
	})

	$("body").delegate(".delete", "click", function(data){
		
		console.log(this.parentElement.id);
		var target = this.parentElement.parentElement;


		$.post("/posts/remove_term", {'id':this.parentElement.id}, function(data){
				target.remove();
		})

	})
})
</script>

app/views/posts/list_textbooks.html.erb
<h1>教科书列表</h1>

<div class="container">


			<div class="row">
				
				<h5 class="">
					<input type="text" value="" placeholder="" id="new-textbook">
					<div class="btn" id="add-textbook">添加</div>
					<div class="btn" id="cancel-add">取消</div>
				</h5>
							
			</div>

	<div class="row">
		<div id="textbooks" class="span8">
			<% @textbooks.each do |textbook| %>
			<div class="row">
				
				<h5 class="palette palette-firm" id="<%= textbook.id %>">
					<span><%= textbook.title %></span>
					<span class="fui-new-24 pull-right relax hide"></span>
					<span class="fui-cross-24 pull-right relax delete"></span>
				</h5>
			</div>
			<% end %>

		</div>
	</div>


</div>

<script>
$(function(){
	$("#add-textbook").click(function(){

		$.post("/posts/add_textbook", {'name':$("#new-textbook").val()}, function(){
				$("#textbooks").append('<div class="row"><h5 class="palette palette-firm"><span> ' + $("#new-textbook").val() + ' </span><span class="fui-new-24 pull-right relax hide"></span><span class="fui-cross-24 pull-right relax delete"></></span></h5></div>');

				$("#new-textbook").val('')
		})
	})

	$("#cancel-add").click(function(){
		$("#new-textbook").val('')
	})

	$("body").delegate(".delete", "click", function(data){
		
		console.log(this.parentElement.id);
		var target = this.parentElement.parentElement;


		$.post("/posts/remove_textbook", {'id':this.parentElement.id}, function(data){
				target.remove();
		})

	})
})
</script>

app/views/posts/new.html.erb
<%= form_tag('/posts/new' , :method => "post", :class => "form-horizontal span9") do |f| %>
  <legend>提交课文</legend>
  <div class="control-group">
    <label class="control-label" for="title">标题</label>
    <div class="controls">
      <%= text_field_tag'article[title]', nil,  :class => "input-xxlarge" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="subtitle">副标题</label>
    <div class="controls">
      <%= text_field_tag'article[subtitle]', nil,  :class => "input-xxlarge" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="author">作者</label>
    <div class="controls">
      <%= collection_select :article, :author_id, Author.all, :id, :name, {},  :class => "input-xxlarge" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="textbook">教材</label>
    <div class="controls">
      <%= collection_select :article, :textbook_id, Textbook.all, :id, :title, {},  :class => "input-xxlarge" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="term">学期</label>
    <div class="controls">
      <%= collection_select :article, :term_id, Term.all, :id, :title, {},  :class => "input-xxlarge" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="info">相关材料</label>
    <div class="controls">
      <%= text_area_tag 'article[info]', nil, :size => "25x10",  :class => "input-xxlarge" %>
    </div> 
  </div>

  <div class="control-group">
    <div class="controls">
      <button id="check" class="btn" type="button">分析</button>
    </div>
  </div>

  <legend>分析结果</legend>

  <div class="control-group">
    <label class="control-label" for="article">原文</label>
    <div class="controls">
      <pre id="sentences" class="help-block">待分析</pre>
    </div>
  </div>

  <div id='ss'>
  </div>

  <div class="control-group">
    <label class="control-label" for="sentences">content</label>
    <div class="controls" >
      <textarea id="content" name="article[content]"></textarea>
    </div>
  </div>


  <div class="control-group">
    <div class="controls">
      <%= submit_tag "提交", :class => "btn" %>
    </div>
  </div>

<% end %>




<script type="text/javascript">
$(function(){
  $('#check').click(function(){
    var raw = $('#editor').val().trim().split("\n");
    var original = '';
    var sentences = [];

    for (var i = 0; i < raw.length; i++) {
      var raw_line = raw[i];
      if(raw_line=='#'){
        $("#content").append('\n\n');
        // ...
      } else {
        //var re = /(\[.+?\])/g ;
        //var spans = sentence.split(re);
        var spans = raw_line.match(/\[.+?\]/g) || [];
        var line =  raw_line.replace(/\[|\]/g,'');

        console.log(raw_line)
        console.log(line)
        console.log(spans)

        var sentence_text = '<div class="control-group">    <label class="control-label" for="article">句子</label><div class="controls">';
        sentence_text += '<div class="input-prepend"><span class="add-on tag"><i class="">句子</i></span><input class="input-xxlarge" name="sentences[][content]" type="text" value="' + line + '"></div>';
        sentence_text += '<div class="input-prepend"><span class="add-on tag"><i class="">翻译</i></span><input class="input-xxlarge" name="sentences[][translation]" type="text"></div>';

        if(spans.length > 0){
          for (var j = 0; j < spans.length; j++) {
            sentence_text += '<br><br>';
            sentence_text += '<div class="input-prepend"><span class="add-on tag"><i class="">单词</i></span><input class="input-xxlarge" name="sentences[][words][][content]" type="text" value="' + spans[j] + '"></div>';
            sentence_text += '<div class="input-prepend"><span class="add-on tag"><i class="">翻译</i></span><input class="input-large" type="text" id="" name="sentences[][words][][translation]"></div>';
            sentence_text += '<div class="input-prepend"><span class="add-on tag"><i class="">词性</i></span><input class="input-large" type="text" id="" name="sentences[][words][][kind]"></div>';
            sentence_text += '<div class="input-prepend"><span class="add-on tag"><i class="">错误项</i></span><input class="input-large" type="text" id="" name="sentences[][words][][mistakes]"></div>';
          };          
        }

        sentence_text += '</div></div>';

        $("#ss").append(sentence_text);
        $("#content").append(line);
      }
    };
  })
})
</script>

app/views/posts/result.html.erb
<h1>Posts#result</h1>
<p>Find me in app/views/posts/result.html.erb</p>

app/views/posts/show.html.erb
<%= form_tag('/posts/new' , :method => "post", :class => "form-horizontal span9") do |f| %>
  <legend>课文</legend>
  <div class="control-group">
    <label class="control-label" for="title">标题</label>
    <div class="controls">
      <%= @article.title %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="subtitle">副标题</label>
    <div class="controls">
      <%= @article.subtitle %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="author">作者</label>
    <div class="controls">
      <%= @article.author.name %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="textbook">教材</label>
    <div class="controls">
      <%= @article.textbook.title %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="term">学期</label>
    <div class="controls">
      <%= @article.term.title %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="info">相关材料</label>
    <div class="controls">
      <%= @article.info %>
    </div> 
  </div>
  <div class="control-group">
    <label class="control-label" for="editor">课文</label>
    <div class="controls">
      <%= @article。content %>
    </div>
  </div>

  <div id='ss'>
    <% puts @article %>
    <% if @article %>
    <% @article.sentences.each do |s| %>
    <div class="control-group">    
      <label class="control-label" for="article">句子</label>
      <div class="controls">
      <div class="input-prepend">
        <span class="add-on tag"><i class="">句子</i></span><input class="input-xxlarge" name="sentences[][content]" type="text" value="<%= s.content %>">
      </div>
      <div class="input-prepend">
        <span class="add-on tag"><i class="">翻译</i></span><input class="input-xxlarge" name="sentences[][translation]" type="text" value="<%= s.translation %>">
      </div>
      <br><br>
      <% s.words.each do |w| %>
        <div class="input-prepend"><span class="add-on tag"><i class="">单词</i></span><input class="input-xxlarge" name="sentences[][words][][content]" type="text"  value="<%= w.content %>"></></div>
        <div class="input-prepend"><span class="add-on tag"><i class="">翻译</i></span><input class="input-large" type="text" id="" name="sentences[][words][][translation]" value="<%= w.translation %>"></></div>
        <div class="input-prepend"><span class="add-on tag"><i class="">词性</i></span><input class="input-large" type="text" id="" name="sentences[][words][][kind]" value="<%= w.kind %>"></></div>
        <div class="input-prepend"><span class="add-on tag"><i class="">错误项</i></span><input class="input-large" type="text" id="" name="sentences[][words][][mistakes]" value="<%= w.mistakes %>"></div>
      <% end %>
    </div>
    </div>
    <% end %>
    <% end %>
  </div>


<% end %>




<script type="text/javascript">
$(function(){
  $('#check').click(function(){
    var raw = $('#editor').val().trim().split("\n");
    var original = '';
    var sentences = [];

    for (var i = 0; i < raw.length; i++) {
      var raw_line = raw[i];
      if(raw_line=='#'){
        $("#content").append('\n\n');
        // ...
      } else {
        //var re = /(\[.+?\])/g ;
        //var spans = sentence.split(re);
        var spans = raw_line.match(/\[.+?\]/g) || [];
        var line =  raw_line.replace(/\[|\]/g,'');

        console.log(raw_line)
        console.log(line)
        console.log(spans)

        var sentence_text = '<div class="control-group">    <label class="control-label" for="article">句子</label><div class="controls">';
        sentence_text += '<div class="input-prepend"><span class="add-on tag"><i class="">句子</i></span><input class="input-xxlarge" name="sentences[][content]" type="text" value="' + line + '"></div>';
        sentence_text += '<div class="input-prepend"><span class="add-on tag"><i class="">翻译</i></span><input class="input-xxlarge" name="sentences[][translation]" type="text"></div>';

        if(spans.length > 0){
          for (var j = 0; j < spans.length; j++) {
            sentence_text += '<br><br>';
            sentence_text += '<div class="input-prepend"><span class="add-on tag"><i class="">单词</i></span><input class="input-xxlarge" name="sentences[][words][][content]" type="text" value="' + spans[j] + '"></div>';
            sentence_text += '<div class="input-prepend"><span class="add-on tag"><i class="">翻译</i></span><input class="input-large" type="text" id="" name="sentences[][words][][translation]"></div>';
            sentence_text += '<div class="input-prepend"><span class="add-on tag"><i class="">词性</i></span><input class="input-large" type="text" id="" name="sentences[][words][][kind]"></div>';
            sentence_text += '<div class="input-prepend"><span class="add-on tag"><i class="">错误项</i></span><input class="input-large" type="text" id="" name="sentences[][words][][mistakes]"></div>';
          };          
        }

        sentence_text += '</div></div>';

        $("#ss").append(sentence_text);
        $("#content").append(line);
      }
    };
  })
})
</script>

app/views/posts/users.html.erb
<h1>Posts#users</h1>
<p>Find me in app/views/posts/users.html.erb</p>